### ISSUE TITLE
Is the dat boi file supposed to play audio?

### ISSUE THREAD

**Issue by couchpotatochip21** [wavetro/Other#1]
If so I do not hear it.

**Comment by wavetro** [comment]
Hi! No unfortunately, it doesn't have the original audio file because I lost it before publishing this, so it just has the leftover keyframes. 

You can delete the existing animation by entering Pose Mode on the rig, selecting all the mouth bones, and deleting everything that appears in the Graph Editor. To add audio to the project, simply drag-and-drop an audio or video file onto the Video Sequencer, and then you can either animate the bones manually with keyframes, or look into the Blender feature "[Bake Sound to F-Curve](https://www.youtube.com/watch?v=Ig7iAGV2am8)" which is what I used. Hope that helps!
